#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyApp_Server.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BabyAppDB")]
	public partial class BabyAppDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertBabyAppTB(BabyAppTB instance);
    partial void UpdateBabyAppTB(BabyAppTB instance);
    partial void DeleteBabyAppTB(BabyAppTB instance);
    #endregion
		
		public BabyAppDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BabyAppDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BabyAppDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BabyAppDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BabyAppDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BabyAppDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BabyAppTB> BabyAppTB
		{
			get
			{
				return this.GetTable<BabyAppTB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BabyAppTB")]
	public partial class BabyAppTB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Context;
		
		private System.Nullable<bool> _sendCheck;
		
		private System.Nullable<System.DateTime> _sendTime;
		
		private System.Nullable<System.DateTime> _RecodeDateTime;
		
		private string _ImgPath;
		
		private string _ImgMime;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnContextChanging(string value);
    partial void OnContextChanged();
    partial void OnsendCheckChanging(System.Nullable<bool> value);
    partial void OnsendCheckChanged();
    partial void OnsendTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnsendTimeChanged();
    partial void OnRecodeDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnRecodeDateTimeChanged();
    partial void OnImgPathChanging(string value);
    partial void OnImgPathChanged();
    partial void OnImgMimeChanging(string value);
    partial void OnImgMimeChanged();
    #endregion
		
		public BabyAppTB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Context", DbType="NVarChar(1000)")]
		public string Context
		{
			get
			{
				return this._Context;
			}
			set
			{
				if ((this._Context != value))
				{
					this.OnContextChanging(value);
					this.SendPropertyChanging();
					this._Context = value;
					this.SendPropertyChanged("Context");
					this.OnContextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendCheck", DbType="Bit")]
		public System.Nullable<bool> sendCheck
		{
			get
			{
				return this._sendCheck;
			}
			set
			{
				if ((this._sendCheck != value))
				{
					this.OnsendCheckChanging(value);
					this.SendPropertyChanging();
					this._sendCheck = value;
					this.SendPropertyChanged("sendCheck");
					this.OnsendCheckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> sendTime
		{
			get
			{
				return this._sendTime;
			}
			set
			{
				if ((this._sendTime != value))
				{
					this.OnsendTimeChanging(value);
					this.SendPropertyChanging();
					this._sendTime = value;
					this.SendPropertyChanged("sendTime");
					this.OnsendTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecodeDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> RecodeDateTime
		{
			get
			{
				return this._RecodeDateTime;
			}
			set
			{
				if ((this._RecodeDateTime != value))
				{
					this.OnRecodeDateTimeChanging(value);
					this.SendPropertyChanging();
					this._RecodeDateTime = value;
					this.SendPropertyChanged("RecodeDateTime");
					this.OnRecodeDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgPath", DbType="NVarChar(500)")]
		public string ImgPath
		{
			get
			{
				return this._ImgPath;
			}
			set
			{
				if ((this._ImgPath != value))
				{
					this.OnImgPathChanging(value);
					this.SendPropertyChanging();
					this._ImgPath = value;
					this.SendPropertyChanged("ImgPath");
					this.OnImgPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgMime", DbType="NVarChar(100)")]
		public string ImgMime
		{
			get
			{
				return this._ImgMime;
			}
			set
			{
				if ((this._ImgMime != value))
				{
					this.OnImgMimeChanging(value);
					this.SendPropertyChanging();
					this._ImgMime = value;
					this.SendPropertyChanged("ImgMime");
					this.OnImgMimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
